### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by pribadihcr** [hosang/gossipnet#1]
Hi @hosang,

Where is the pretrained model define in  .yaml pretrained_model: /BS/bbox_nms_net2/work/tf-models/resnet_v1_101.ckpt

Thanks

**Comment by hosang** [comment]
That experiment is not actually using image features, so I removed the line from the config file. It should be possible to train without having the resnet to initialize from. (The code does support image features, though.)

If you want to use it anyway, you can get pretrained resnets here: https://github.com/tensorflow/models/tree/master/research/slim
