### ISSUE TITLE
Error in compiling: make: *** [nms_net/matching_module/det_matching.so] Fehler 1

### ISSUE THREAD

**Issue by arasharchor** [hosang/gossipnet#10]
Hi @hosang,

I tried to compile the repo, but I am getting the following error. 
(objdetTF3) azim_se@othrys2:~/azim_se/projects/detection/gossipnet$ make
g++ -std=c++11 -shared nms_net/matching_module/det_matching.cc -o nms_net/matching_module/det_matching.so -fPIC -I "/home/azim_se/.virtualenvs/objdetTF3/lib/python3.5/site-packages/tensorflow/include" -O2
In file included from nms_net/matching_module/det_matching.cc:5:0:
nms_net/matching_module/det_matching.cc: In member function ‘void DetectionMatchingOp<T>::Compute(tensorflow::OpKernelContext*)’:
/home/azim_se/.virtualenvs/objdetTF3/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:1538:3: error: expected ‘;’ before ‘do’
   do {                                                 \
   ^
nms_net/matching_module/det_matching.cc:91:5: note: in expansion of macro ‘OP_REQUIRES’
     OP_REQUIRES(context, ious.dimension(1) == ignore.dimension(0),
     ^
nms_net/matching_module/det_matching.cc:95:5: error: expected ‘;’ before ‘argsort’
     argsort<T>(score, &det_order);
     ^
Makefile:19: die Regel für Ziel „nms_net/matching_module/det_matching.so“ scheiterte
make: *** [nms_net/matching_module/det_matching.so] Fehler 1

Here is my system configuration:
Ubuntu 16.04
Tensorflow 1.8
Cuda 9.0
Cudnn 7.0
GPU: Titan X Pascal
Python 3.5.2

Here is the system path configuration:
echo $PATH
/home/azim_se/.virtualenvs/objdetTF3/bin:/usr/local/cuda-9.0/bin:/home/azim_se/MyProjects/pytorch/eigen3/compiled:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/azim_se/softwares/pycharm/bin:/home/azim_se/softwares/eclipse:/home/azim_se/MyProjects/bin:/home/azim_se/MATLAB/R2016b/bin:/home/azim_se/.local/bin:/home/azim_se/softwares/tensorRT/4.0.0.3-ubuntu16.04-cuda9.0-cudnn7.0.5/bin
echo $LD_LIBRARY_PATH
/home/azim_se/softwares/cuDNN/9.0-v7.0.5-ubuntu16.04/lib64:/home/azim_se/MyProjects/pytorch/eigen3:/home/azim_se/MyProjects/pytorch/eigen3/build:/usr/local/cuda-9.0/lib64:/usr/local/opencv-3.4.1/lib/x86_64-linux-gnu:/home/azim_se/softwares/tensorRT/4.0.0.3-ubuntu16.04-cuda9.0-cudnn7.0.5/lib:/home/azim_se/.local/lib:/home/azim_se/MyProjects/pytorch/nccl/compiled/lib
echo $PYTHONPATH
/home/azim_se/projects/detection/ModelsTF/research:/home/azim_se/projects/detection//ModelsTF/research/slim

**Comment by SamDon87** [comment]
Just add the two missing ";"

`OP_REQUIRES(..);`

You also should include numeric for iota.

**Comment by arasharchor** [comment]
@SamDon87 Thanks for your help.
I added those missing ";"
no more error, just warnings: /home/azim_se/.virtualenvs/objdetTF3/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(213): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

I could not find where I should include numeric for iota. Could you guide me to that?

**Comment by SamDon87** [comment]
I think you don't need the include if it works fine.

I built the module for windows and got an missing iota error.

**Comment by arasharchor** [comment]
@SamDon87 got it. Thanks a lot for your help :)
