### ISSUE TITLE
roi_pooling.so: undefined symbol

### ISSUE THREAD

**Issue by pribadihcr** [hosang/gossipnet#3]
Hi @hosang,

I got the following error:

tensorflow.python.framework.errors_impl.NotFoundError: /work/DL/code/gossipnet/nms_net/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE

**Comment by pribadihcr** [comment]
I add -D_GLIBCXX_USE_CXX11_ABI=0 in Makefile

**Comment by UniLauX** [comment]
hi@hosang,
I got the following error:
tensorflow.python.framework.errors_impl.NotFoundError: /home/uni/Lab/projects/Python/gossipnet/nms_net/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZTIN10tensorflow8OpKernel E

**Comment by UniLauX** [comment]
@pribadihcr  I add this one but doesn't help. Any advice, thanks~
I add -D_GLIBCXX_USE_CXX11_ABI=0 in Makefile

I use python3.5.
