### ISSUE TITLE
KeyError: 'gt_classes'

### ISSUE THREAD

**Issue by pribadihcr** [hosang/gossipnet#5]
Hi @hosang,

I got following error:
  File "train.py", line 87, in load_and_enqueue
    food = {ph: batch[name] for (name, ph) in placeholders}
  File "train.py", line 87, in <dictcomp>
    food = {ph: batch[name] for (name, ph) in placeholders}
KeyError: 'gt_classes'

look like batch has key name gt_classes

**Comment by hosang** [comment]
Can you tell me what you're running? On which data are you trying to train? Is it possible there are no annotations on that data?

**Comment by pribadihcr** [comment]
I just run python train.py. 
and use COCO dataset. because I dont have image_info_train2014.json so I rename instances_train2014.json in coco/annotations

**Comment by hosang** [comment]
Don't rename the files. They are called image info only for the test set because there are no annotations on the test set.

**Comment by hosang** [comment]
Did not renaming files resolve the issue for you?

**Comment by pribadihcr** [comment]
Hi @hosang,

Yes, I didnt renaming file. The error occur because the coco path is wrong. Thanks

**Comment by UniLauX** [comment]
@pribadihcr how do you solve this problem later? I came across the same problem..
@hosang where can we get the 'image_info_train2014.json '  files if it was different from  "instances_train2014.json" , the same for 'image_info_minval2014.json' .. thanks~

**Comment by UpCoder** [comment]
@UniLauX You need put the file in project_dir/data/coco/annotation/, and everything is ok.
Please see https://github.com/hosang/gossipnet/issues/14
